version: '3.6'
services:
  web:
    image: 'registry.gitlab.cn/omnibus/gitlab-jh:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.26.126.122'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'

  runner:
   image: gitlab/gitlab-runner:latest
   restart: always
   volumes:
     - '/var/run/docker.sock:/var/run/docker.sock'
     - './runner-config:/etc/gitlab-runner'
     - './sonar-scanner-4.8.0.2856-linux/:/usr/local/sonar-scanner/'
